[
    {
        "model": "error.Error",
        "pk": null,
        "fields": {
            "name": "unknown",
            "title": "Unknown",
            "description": "The cause of this failure is unknown. System administrators should investigate this failure to determine the true cause and make sure it is correctly tracked in the future.",
            "category": "SYSTEM",
            "created": "2015-03-11T00:00:00.0Z",
            "last_modified": "2015-03-11T00:00:00.0Z"
        }
    },
    {
        "model": "error.Error",
        "pk": null,
        "fields": {
            "name": "database",
            "title": "Database",
            "description": "A query against the Scale database failed.",
            "category": "SYSTEM",
            "created": "2015-03-11T00:00:00.0Z",
            "last_modified": "2015-03-11T00:00:00.0Z"
        }
    },
    {
        "model": "error.Error",
        "pk": null,
        "fields": {
            "name": "filesystem-io",
            "title": "Filesystem IO",
            "description": "An IO operation on the node's local filesystem failed.",
            "category": "SYSTEM",
            "created": "2015-03-11T00:00:00.0Z",
            "last_modified": "2015-03-11T00:00:00.0Z"
        }
    },
    {
        "model": "error.Error",
        "pk": null,
        "fields": {
            "name": "nfs",
            "title": "NFS",
            "description": "An NFS (Network File System) operation failed.",
            "category": "SYSTEM",
            "created": "2015-03-11T00:00:00.0Z",
            "last_modified": "2015-03-11T00:00:00.0Z"
        }
    }
]